// <auto-generated />
using System;
using ERP.Core.Database.Domain.Enums;
using ERP.Core.Manager.Api.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ERP.Core.Manager.Api.Infrastructure.Persistence.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "catalog_type_enum", new[] { "banks", "branches", "departaments", "document_types", "exchange_rates", "job_positions", "work_areas" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "collaborator_status_enum", new[] { "active", "inactive", "subsidy", "suspended", "terminated", "testing_process", "vacation" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "currency_enum", new[] { "nio", "usd" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "deduction_type_enum", new[] { "advance_christmas_bonus", "late_arrivals", "loans", "other_deductions" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "gender_type_enum", new[] { "man", "women" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "identification_type_enum", new[] { "cedula", "cedula_residencia", "pasaporte" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "marital_status_enum", new[] { "divorced", "domestic_partner", "married", "none", "other", "separated", "single", "widowed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payroll_status_enum", new[] { "cancelled", "closed", "completed", "progress" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "permission_type_enum", new[] { "create", "delete", "read", "update" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "permit_application_status_enum", new[] { "approved", "cancelled", "pending", "rejected" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "permit_application_type_enum", new[] { "compensatory_time", "donated_vacations", "medical_appointment", "paid_leave", "special_leave", "unpaid_leave", "vacation" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "catalog_type_enum", new[] { "branches", "work_areas", "job_positions", "document_types", "banks", "exchange_rates", "departaments" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "collaborator_status_enum", new[] { "active", "inactive", "vacation", "subsidy", "suspended", "terminated", "testing_process" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "currency_enum", new[] { "nio", "usd" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "deduction_type_enum", new[] { "loans", "advance_christmas_bonus", "late_arrivals", "other_deductions" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "gender_type_enum", new[] { "man", "women" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "identification_type_enum", new[] { "cedula", "pasaporte", "cedula_residencia" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "marital_status_enum", new[] { "none", "single", "married", "divorced", "widowed", "domestic_partner", "separated", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "payroll_status_enum", new[] { "progress", "closed", "cancelled", "completed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "permission_type_enum", new[] { "read", "create", "update", "delete" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "permit_application_status_enum", new[] { "pending", "approved", "rejected", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "permit_application_type_enum", new[] { "vacation", "medical_appointment", "compensatory_time", "paid_leave", "unpaid_leave", "special_leave", "donated_vacations" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "role_type_enum", new[] { "administrator", "supervisor", "manager", "operator" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "salary_type_enum", new[] { "fixed", "variable", "professional_services" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "user_status_enum", new[] { "active", "inactive", "locked" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "user_type_enum", new[] { "standard_user", "employee_self_service" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "role_type_enum", new[] { "administrator", "manager", "operator", "supervisor" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "salary_type_enum", new[] { "fixed", "professional_services", "variable" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_status_enum", new[] { "active", "inactive", "locked" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_type_enum", new[] { "employee_self_service", "standard_user" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Auth.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("description");

                    b.Property<string>("PermissionName")
                        .HasColumnType("text")
                        .HasColumnName("permission_name");

                    b.Property<string>("PermissionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permission_type");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_permission_id");

                    b.HasIndex("RoleId");

                    b.ToTable("permissions", "public");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Auth.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("role_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("role_name");

                    b.Property<RoleType>("RoleType")
                        .HasColumnType("role_type_enum")
                        .HasColumnName("role_type_Enum");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_role_id");

                    b.ToTable("roles", "public");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Auth.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Device")
                        .HasColumnType("text")
                        .HasColumnName("device");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_session_id");

                    b.HasIndex("UserId");

                    b.ToTable("sessions", "public");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AreaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fullname");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identification_number");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.Property<UserStatus>("UserStatus")
                        .HasColumnType("user_status_enum")
                        .HasColumnName("user_status");

                    b.Property<UserType>("UserType")
                        .HasColumnType("user_type_enum")
                        .HasColumnName("user_type");

                    b.HasKey("Id");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Auth.UserModuleRoles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_module_role_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("module_code");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserProfileId", "ModuleCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Unique_User_Module_Role");

                    b.ToTable("user_module_roles", "public");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Auth.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_profile_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("users_profiles", "public");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Catalogs.Catalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("catalog_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CatalogName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("catalog_name");

                    b.Property<CatalogType>("CatalogType")
                        .HasColumnType("catalog_type_enum")
                        .HasColumnName("catalog_type");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsGlobal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_global");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "CatalogName", "CatalogType")
                        .IsUnique()
                        .HasDatabaseName("IX_catalogs_company_type");

                    b.ToTable("catalogs", "public");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Catalogs.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("company_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Alias")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("alias");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("CompanieName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("NeutralImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("neutral_image_url");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_companies_code");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("IX_companies_id");

                    b.ToTable("companies", "public");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Catalogs.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("module_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("module_name");

                    b.Property<string>("PathRedirect")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("/dashboard")
                        .HasColumnName("path_redirect");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_modules_company_code");

                    b.ToTable("modules", "public");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Catalogs.SubCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sub_catalog_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CatalogId")
                        .HasColumnType("integer")
                        .HasColumnName("catalog_id");

                    b.Property<string>("CatalogName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("catalog_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.ToTable("sub_catalogs", "public");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Payrolls.Collaborator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("collaborator_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CollaboratorCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("collaborator_code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FirstLastname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_lastname");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<GenderType>("Gender")
                        .HasColumnType("gender_type_enum")
                        .HasColumnName("gender");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identification_number");

                    b.Property<IdentificationType>("IdentificationType")
                        .HasColumnType("identification_type_enum")
                        .HasColumnName("identification_type");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("text")
                        .HasColumnName("picture_url");

                    b.Property<string>("RegisteredBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registered_by");

                    b.Property<string>("SecondLastname")
                        .HasColumnType("text")
                        .HasColumnName("second_lastname");

                    b.Property<string>("SecondName")
                        .HasColumnType("text")
                        .HasColumnName("second_name");

                    b.Property<CollaboratorStatus>("Status")
                        .HasColumnType("collaborator_status_enum")
                        .HasColumnName("status");

                    b.Property<string>("ThirdName")
                        .HasColumnType("text")
                        .HasColumnName("third_name");

                    b.HasKey("Id");

                    b.HasIndex("CollaboratorCode")
                        .IsUnique()
                        .HasDatabaseName("IX_collaborators_collaborator_code");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("IX_collaborator_id");

                    b.HasIndex("IdentificationNumber")
                        .HasDatabaseName("IX_collaborators_identification_number");

                    b.ToTable("collaborators", "public");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Payrolls.Deduction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("deduction_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CollaboratorId")
                        .HasColumnType("uuid")
                        .HasColumnName("collaborator_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DeductionType>("Type")
                        .HasColumnType("deduction_type_enum")
                        .HasColumnName("deduction_type");

                    b.HasKey("Id");

                    b.HasIndex("CollaboratorId");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_deduction_id");

                    b.ToTable("deductions", "public");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Payrolls.OrdinaryPayroll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ordinary_payroll_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Bonus")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("bonus");

                    b.Property<Guid>("CollaboratorId")
                        .HasColumnType("uuid")
                        .HasColumnName("collaborator_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Deductions")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("deductions");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("GrossSalary")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("gross_salary");

                    b.Property<decimal>("Inss")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("inss");

                    b.Property<decimal>("Ir")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("ir");

                    b.Property<decimal>("Overtime")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("overtimes");

                    b.Property<Guid>("PayrollId")
                        .HasColumnType("uuid")
                        .HasColumnName("payroll_id");

                    b.Property<decimal>("TotalDeducctions")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_deductions");

                    b.Property<decimal>("TotalToPay")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_to_pay");

                    b.Property<decimal>("Vacations")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("vacations");

                    b.HasKey("Id");

                    b.HasIndex("CollaboratorId");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_ordinary_payroll_id");

                    b.HasIndex("PayrollId");

                    b.ToTable("ordinary_payrolls", "public");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Payrolls.Payroll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("payroll_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<PayrollStatus>("Status")
                        .HasColumnType("payroll_status_enum")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalToPay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_to_pay");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_payroll_id");

                    b.ToTable("payrolls", "public");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Payrolls.PermitApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("permit_application_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AdditionalData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("additional_data");

                    b.Property<string>("AdministratorFullName")
                        .HasColumnType("text")
                        .HasColumnName("administrator_fullname");

                    b.Property<decimal>("AmountDays")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("amount_days");

                    b.Property<string>("CollaboratorCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("collaborator_code");

                    b.Property<Guid>("CollaboratorId")
                        .HasColumnType("uuid")
                        .HasColumnName("collaborator_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<bool?>("FirtsStepApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("first_step_approved");

                    b.Property<string>("IdentificationCollaboratorToReceive")
                        .HasColumnType("text")
                        .HasColumnName("identification_collaborator_to_receive");

                    b.Property<string>("ManagerFullname")
                        .HasColumnType("text")
                        .HasColumnName("manager_fullname");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requested_by");

                    b.Property<bool?>("SecondStepApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("second_step_approved");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<PermitApplicationStatus>("Status")
                        .HasColumnType("permit_application_status_enum")
                        .HasColumnName("status");

                    b.Property<PermitApplicationType>("Type")
                        .HasColumnType("permit_application_type_enum")
                        .HasColumnName("permit_application_type");

                    b.HasKey("Id");

                    b.HasIndex("CollaboratorId");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_permit_application_id");

                    b.ToTable("permit_applications", "public");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Payrolls.PersonalInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("personal_information_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birthdate");

                    b.Property<Guid>("CollaboratorId")
                        .HasColumnType("uuid")
                        .HasColumnName("collaborator_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DepartamentId")
                        .HasColumnType("integer")
                        .HasColumnName("departament_id");

                    b.Property<MaritalStatus>("MaritalStatus")
                        .HasColumnType("marital_status_enum")
                        .HasColumnName("marital_status");

                    b.Property<string>("PersonalEmail")
                        .HasColumnType("text")
                        .HasColumnName("personal_email");

                    b.Property<string>("PersonalPhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("personal_phone_number");

                    b.HasKey("Id");

                    b.HasIndex("CollaboratorId")
                        .IsUnique();

                    b.HasIndex("DepartamentId");

                    b.ToTable("personal_informations", "public");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Payrolls.Salary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("salary_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("AmountInForeign")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("amount_in_foreign");

                    b.Property<decimal>("AmountInLocal")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("amount_in_local");

                    b.Property<decimal>("AmountSalary")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("amount_salary");

                    b.Property<int>("BankSubCatalogId")
                        .HasColumnType("integer")
                        .HasColumnName("bank_id");

                    b.Property<Guid>("CollaboratorId")
                        .HasColumnType("uuid")
                        .HasColumnName("collaborator_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Currency>("Currency")
                        .HasColumnType("currency_enum")
                        .HasColumnName("currency");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<SalaryType>("SalaryType")
                        .HasColumnType("salary_type_enum")
                        .HasColumnName("salary_type");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("CollaboratorId")
                        .IsUnique();

                    b.ToTable("salaries", "public");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Payrolls.Vacation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("vacation_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("AvailableVacations")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("available_vacations");

                    b.Property<Guid>("CollaboratorId")
                        .HasColumnType("uuid")
                        .HasColumnName("collaborator_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("DonatedVacation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("donated_vacation");

                    b.Property<decimal>("EnjoyedVacation")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("enjoyed_vacation");

                    b.Property<decimal>("GeneredVacation")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("genered_vacation");

                    b.HasKey("Id");

                    b.HasIndex("CollaboratorId")
                        .IsUnique();

                    b.ToTable("vacations", "public");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Payrolls.WorkPositionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("work_position_history_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CollaboratorId")
                        .HasColumnType("uuid")
                        .HasColumnName("collaborator_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkPositionId")
                        .HasColumnType("integer")
                        .HasColumnName("work_position_id");

                    b.HasKey("Id");

                    b.HasIndex("CollaboratorId");

                    b.HasIndex("WorkPositionId");

                    b.ToTable("work_position_histories", "public");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Payrolls.WorkingInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("working_information_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("text")
                        .HasColumnName("bank_account_number");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("CollaboratorId")
                        .HasColumnType("uuid")
                        .HasColumnName("collaborator_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("DepartureDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departure_date");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entry_date");

                    b.Property<string>("InssNumber")
                        .HasColumnType("text")
                        .HasColumnName("inss_number");

                    b.Property<int>("WorkAreaId")
                        .HasColumnType("integer")
                        .HasColumnName("work_area_id");

                    b.Property<string>("WorkEmail")
                        .HasColumnType("text")
                        .HasColumnName("work_email");

                    b.Property<string>("WorkPhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("work_phone_number");

                    b.Property<int>("WorkPositionId")
                        .HasColumnType("integer")
                        .HasColumnName("work_position_id");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CollaboratorId")
                        .IsUnique();

                    b.HasIndex("WorkAreaId");

                    b.HasIndex("WorkPositionId");

                    b.ToTable("working_information", "public");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Auth.Permission", b =>
                {
                    b.HasOne("ERP.Core.Database.Domain.Entities.Auth.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Auth.Session", b =>
                {
                    b.HasOne("ERP.Core.Database.Domain.Entities.Auth.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Auth.UserModuleRoles", b =>
                {
                    b.HasOne("ERP.Core.Database.Domain.Entities.Catalogs.Module", "Module")
                        .WithMany("UserModuleRoles")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Core.Database.Domain.Entities.Auth.Role", "Role")
                        .WithMany("UserModuleRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Core.Database.Domain.Entities.Auth.UserProfile", "UserProfile")
                        .WithMany("UserModuleRole")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Role");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Auth.UserProfile", b =>
                {
                    b.HasOne("ERP.Core.Database.Domain.Entities.Catalogs.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Core.Database.Domain.Entities.Auth.User", "User")
                        .WithMany("Profiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Catalogs.Catalog", b =>
                {
                    b.HasOne("ERP.Core.Database.Domain.Entities.Catalogs.Company", "Company")
                        .WithMany("Catalogs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Catalogs.SubCatalog", b =>
                {
                    b.HasOne("ERP.Core.Database.Domain.Entities.Catalogs.Catalog", "Catalog")
                        .WithMany("SubCatalogs")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Payrolls.Collaborator", b =>
                {
                    b.HasOne("ERP.Core.Database.Domain.Entities.Catalogs.Company", "Company")
                        .WithMany("Collaborators")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Payrolls.Deduction", b =>
                {
                    b.HasOne("ERP.Core.Database.Domain.Entities.Payrolls.Collaborator", "Collaborator")
                        .WithMany("Deductions")
                        .HasForeignKey("CollaboratorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Collaborator");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Payrolls.OrdinaryPayroll", b =>
                {
                    b.HasOne("ERP.Core.Database.Domain.Entities.Payrolls.Collaborator", "Collaborator")
                        .WithMany("OrdinaryPayrolls")
                        .HasForeignKey("CollaboratorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Core.Database.Domain.Entities.Payrolls.Payroll", "Payroll")
                        .WithMany("OrdinaryPayrolls")
                        .HasForeignKey("PayrollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collaborator");

                    b.Navigation("Payroll");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Payrolls.Payroll", b =>
                {
                    b.HasOne("ERP.Core.Database.Domain.Entities.Catalogs.Company", "Company")
                        .WithMany("Payrolls")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Payrolls.PermitApplication", b =>
                {
                    b.HasOne("ERP.Core.Database.Domain.Entities.Payrolls.Collaborator", "Collaborator")
                        .WithMany("PermitApplications")
                        .HasForeignKey("CollaboratorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Collaborator");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Payrolls.PersonalInformation", b =>
                {
                    b.HasOne("ERP.Core.Database.Domain.Entities.Payrolls.Collaborator", "Collaborator")
                        .WithOne("PersonalInformation")
                        .HasForeignKey("ERP.Core.Database.Domain.Entities.Payrolls.PersonalInformation", "CollaboratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Core.Database.Domain.Entities.Catalogs.SubCatalog", "Departament")
                        .WithMany()
                        .HasForeignKey("DepartamentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Collaborator");

                    b.Navigation("Departament");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Payrolls.Salary", b =>
                {
                    b.HasOne("ERP.Core.Database.Domain.Entities.Payrolls.Collaborator", "Collaborator")
                        .WithMany("Salaries")
                        .HasForeignKey("CollaboratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collaborator");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Payrolls.Vacation", b =>
                {
                    b.HasOne("ERP.Core.Database.Domain.Entities.Payrolls.Collaborator", "Collaborator")
                        .WithOne("Vacation")
                        .HasForeignKey("ERP.Core.Database.Domain.Entities.Payrolls.Vacation", "CollaboratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collaborator");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Payrolls.WorkPositionHistory", b =>
                {
                    b.HasOne("ERP.Core.Database.Domain.Entities.Payrolls.Collaborator", "Collaborator")
                        .WithMany("WorkPositionHistory")
                        .HasForeignKey("CollaboratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Core.Database.Domain.Entities.Catalogs.SubCatalog", "WorkPosition")
                        .WithMany()
                        .HasForeignKey("WorkPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Collaborator");

                    b.Navigation("WorkPosition");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Payrolls.WorkingInformation", b =>
                {
                    b.HasOne("ERP.Core.Database.Domain.Entities.Catalogs.SubCatalog", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Core.Database.Domain.Entities.Payrolls.Collaborator", "Collaborator")
                        .WithOne("WorkingInformation")
                        .HasForeignKey("ERP.Core.Database.Domain.Entities.Payrolls.WorkingInformation", "CollaboratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Core.Database.Domain.Entities.Catalogs.SubCatalog", "WorkArea")
                        .WithMany()
                        .HasForeignKey("WorkAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Core.Database.Domain.Entities.Catalogs.SubCatalog", "WorkPosition")
                        .WithMany()
                        .HasForeignKey("WorkPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Collaborator");

                    b.Navigation("WorkArea");

                    b.Navigation("WorkPosition");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Auth.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserModuleRoles");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Auth.User", b =>
                {
                    b.Navigation("Profiles");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Auth.UserProfile", b =>
                {
                    b.Navigation("UserModuleRole");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Catalogs.Catalog", b =>
                {
                    b.Navigation("SubCatalogs");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Catalogs.Company", b =>
                {
                    b.Navigation("Catalogs");

                    b.Navigation("Collaborators");

                    b.Navigation("Payrolls");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Catalogs.Module", b =>
                {
                    b.Navigation("UserModuleRoles");
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Payrolls.Collaborator", b =>
                {
                    b.Navigation("Deductions");

                    b.Navigation("OrdinaryPayrolls");

                    b.Navigation("PermitApplications");

                    b.Navigation("PersonalInformation")
                        .IsRequired();

                    b.Navigation("Salaries");

                    b.Navigation("Vacation")
                        .IsRequired();

                    b.Navigation("WorkPositionHistory");

                    b.Navigation("WorkingInformation")
                        .IsRequired();
                });

            modelBuilder.Entity("ERP.Core.Database.Domain.Entities.Payrolls.Payroll", b =>
                {
                    b.Navigation("OrdinaryPayrolls");
                });
#pragma warning restore 612, 618
        }
    }
}
