CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TYPE public.catalog_type_enum AS ENUM ('branches', 'work_areas', 'job_positions', 'document_types', 'banks', 'exchange_rates');
CREATE TYPE public.collaborator_status_enum AS ENUM ('active', 'inactive', 'vacation', 'subsidy', 'suspended', 'terminated', 'testing_process');
CREATE TYPE public.currency_enum AS ENUM ('nio', 'usd');
CREATE TYPE public.gender_type_enum AS ENUM ('man', 'women');
CREATE TYPE public.identification_type_enum AS ENUM ('cedula', 'pasaporte', 'cedula_residencia');
CREATE TYPE public.marital_status_enum AS ENUM ('none', 'single', 'married', 'divorced', 'widowed', 'domestic_partner', 'separated', 'other');
CREATE TYPE public.permission_type_enum AS ENUM ('read', 'create', 'update', 'delete');
CREATE TYPE public.permit_application_status_enum AS ENUM ('pending', 'approved', 'rejected', 'cancelled');
CREATE TYPE public.permit_application_type_enum AS ENUM ('vacation', 'medical_appointment', 'compensatory_time', 'paid_leave', 'unpaid_leave', 'special_leave');
CREATE TYPE public.role_type_enum AS ENUM ('administrator', 'supervisor', 'manager', 'operator');
CREATE TYPE public.salary_type_enum AS ENUM ('fixed', 'variable', 'professional_services');
CREATE TYPE public.user_status_enum AS ENUM ('active', 'inactive', 'locked');
CREATE TYPE public.user_type_enum AS ENUM ('standard_user', 'employee_self_service');
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE public.companies (
    company_id uuid NOT NULL DEFAULT (gen_random_uuid()),
    is_active boolean NOT NULL DEFAULT TRUE,
    code character varying(50),
    alias character varying(100),
    image_url text,
    neutral_image_url text,
    company_name character varying(200),
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_companies" PRIMARY KEY (company_id)
);

CREATE TABLE public.modules (
    module_id uuid NOT NULL DEFAULT (gen_random_uuid()),
    is_active boolean NOT NULL DEFAULT TRUE,
    code text NOT NULL,
    description text,
    module_name character varying(180) NOT NULL,
    path_redirect text NOT NULL DEFAULT '/dashboard',
    image_url text,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_modules" PRIMARY KEY (module_id)
);

CREATE TABLE public.roles (
    role_id uuid NOT NULL DEFAULT (gen_random_uuid()),
    role_name character varying(180) NOT NULL,
    description text,
    "role_type_Enum" role_type_enum NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_roles" PRIMARY KEY (role_id)
);

CREATE TABLE public.users (
    user_id uuid NOT NULL DEFAULT (gen_random_uuid()),
    email text NOT NULL,
    user_name text NOT NULL,
    fullname text NOT NULL,
    password_hash text NOT NULL,
    identification_number text NOT NULL,
    user_type user_type_enum NOT NULL,
    user_status user_status_enum NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_users" PRIMARY KEY (user_id)
);

CREATE TABLE public.catalogs (
    catalog_id integer GENERATED BY DEFAULT AS IDENTITY,
    is_active boolean NOT NULL DEFAULT TRUE,
    catalog_name character varying(150),
    description character varying(500),
    catalog_type catalog_type_enum NOT NULL,
    company_id uuid NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_catalogs" PRIMARY KEY (catalog_id),
    CONSTRAINT "FK_catalogs_companies_company_id" FOREIGN KEY (company_id) REFERENCES public.companies (company_id) ON DELETE CASCADE
);

CREATE TABLE public.collaborators (
    collaborator_id uuid NOT NULL DEFAULT (gen_random_uuid()),
    picture_url text,
    first_name text NOT NULL,
    first_lastname text NOT NULL,
    identification_number text NOT NULL,
    collaborator_code text NOT NULL,
    company_id uuid NOT NULL,
    second_name text,
    third_name text,
    second_lastname text,
    registered_by text NOT NULL,
    gender gender_type_enum NOT NULL,
    status collaborator_status_enum NOT NULL,
    identification_type identification_type_enum NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_collaborators" PRIMARY KEY (collaborator_id),
    CONSTRAINT "FK_collaborators_companies_company_id" FOREIGN KEY (company_id) REFERENCES public.companies (company_id) ON DELETE RESTRICT
);

CREATE TABLE public.permissions (
    permission_id uuid NOT NULL DEFAULT (gen_random_uuid()),
    role_id uuid NOT NULL,
    description character varying(400),
    permission_name text,
    permission_type text NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_permissions" PRIMARY KEY (permission_id),
    CONSTRAINT "FK_permissions_roles_role_id" FOREIGN KEY (role_id) REFERENCES public.roles (role_id) ON DELETE CASCADE
);

CREATE TABLE public.sessions (
    session_id uuid NOT NULL DEFAULT (gen_random_uuid()),
    user_id uuid NOT NULL,
    device text,
    ip_address text,
    refresh_token text NOT NULL,
    "IsActive" boolean NOT NULL,
    company_code text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_sessions" PRIMARY KEY (session_id),
    CONSTRAINT "FK_sessions_users_user_id" FOREIGN KEY (user_id) REFERENCES public.users (user_id) ON DELETE CASCADE
);

CREATE TABLE public.users_profiles (
    user_profile_id uuid NOT NULL DEFAULT (gen_random_uuid()),
    user_id uuid NOT NULL,
    company_id uuid NOT NULL,
    is_active boolean NOT NULL DEFAULT TRUE,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_users_profiles" PRIMARY KEY (user_profile_id),
    CONSTRAINT "FK_users_profiles_companies_company_id" FOREIGN KEY (company_id) REFERENCES public.companies (company_id) ON DELETE CASCADE,
    CONSTRAINT "FK_users_profiles_users_user_id" FOREIGN KEY (user_id) REFERENCES public.users (user_id) ON DELETE CASCADE
);

CREATE TABLE public.sub_catalogs (
    sub_catalog_id integer GENERATED BY DEFAULT AS IDENTITY,
    is_active boolean NOT NULL DEFAULT TRUE,
    catalog_name character varying(150),
    description character varying(500),
    catalog_id integer NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_sub_catalogs" PRIMARY KEY (sub_catalog_id),
    CONSTRAINT "FK_sub_catalogs_catalogs_catalog_id" FOREIGN KEY (catalog_id) REFERENCES public.catalogs (catalog_id) ON DELETE CASCADE
);

CREATE TABLE public.permit_applications (
    permit_application_id uuid NOT NULL DEFAULT (gen_random_uuid()),
    collaborator_id uuid NOT NULL,
    approved_by text,
    rejected_by text,
    collaborator_code text NOT NULL,
    permit_application_type permit_application_type_enum NOT NULL,
    status permit_application_status_enum NOT NULL,
    amount_days integer NOT NULL,
    requested_by text NOT NULL,
    description text,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    start_time time without time zone,
    end_time time without time zone,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_permit_applications" PRIMARY KEY (permit_application_id),
    CONSTRAINT "FK_permit_applications_collaborators_collaborator_id" FOREIGN KEY (collaborator_id) REFERENCES public.collaborators (collaborator_id) ON DELETE RESTRICT
);

CREATE TABLE public.personal_informations (
    personal_information_id uuid NOT NULL DEFAULT (gen_random_uuid()),
    collaborator_id uuid NOT NULL,
    personal_email text,
    personal_phone_number text,
    address text,
    departament text,
    birthdate timestamp with time zone NOT NULL,
    marital_status marital_status_enum NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_personal_informations" PRIMARY KEY (personal_information_id),
    CONSTRAINT "FK_personal_informations_collaborators_collaborator_id" FOREIGN KEY (collaborator_id) REFERENCES public.collaborators (collaborator_id) ON DELETE CASCADE
);

CREATE TABLE public.salaries (
    salary_id uuid NOT NULL DEFAULT (gen_random_uuid()),
    collaborator_id uuid NOT NULL,
    amount_in_local numeric(18,3) NOT NULL,
    amount_in_foreign numeric(18,3) NOT NULL,
    amount_salary numeric(18,3) NOT NULL,
    bank_id integer NOT NULL,
    currency currency_enum NOT NULL,
    salary_type salary_type_enum NOT NULL,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_salaries" PRIMARY KEY (salary_id),
    CONSTRAINT "FK_salaries_collaborators_collaborator_id" FOREIGN KEY (collaborator_id) REFERENCES public.collaborators (collaborator_id) ON DELETE CASCADE
);

CREATE TABLE public.vacations (
    vacation_id uuid NOT NULL DEFAULT (gen_random_uuid()),
    collaborator_id uuid NOT NULL,
    available_vacations numeric(18,4) NOT NULL,
    genered_vacation numeric(18,4) NOT NULL,
    enjoyed_vacation numeric(18,4) NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_vacations" PRIMARY KEY (vacation_id),
    CONSTRAINT "FK_vacations_collaborators_collaborator_id" FOREIGN KEY (collaborator_id) REFERENCES public.collaborators (collaborator_id) ON DELETE CASCADE
);

CREATE TABLE public.user_module_roles (
    user_module_role_id uuid NOT NULL DEFAULT (gen_random_uuid()),
    role_id uuid NOT NULL,
    user_profile_id uuid NOT NULL,
    module_id uuid NOT NULL,
    is_active boolean NOT NULL DEFAULT TRUE,
    module_code text NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_user_module_roles" PRIMARY KEY (user_module_role_id),
    CONSTRAINT "FK_user_module_roles_modules_module_id" FOREIGN KEY (module_id) REFERENCES public.modules (module_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_user_module_roles_roles_role_id" FOREIGN KEY (role_id) REFERENCES public.roles (role_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_user_module_roles_users_profiles_user_profile_id" FOREIGN KEY (user_profile_id) REFERENCES public.users_profiles (user_profile_id) ON DELETE CASCADE
);

CREATE TABLE public.working_information (
    working_information_id uuid NOT NULL DEFAULT (gen_random_uuid()),
    bank_account_number text,
    work_phone_number text,
    work_email text,
    inss_number text,
    departure_date timestamp with time zone,
    collaborator_id uuid NOT NULL,
    "WorkAreaId" integer NOT NULL,
    "WorkPositionId" integer NOT NULL,
    "BranchId" integer NOT NULL,
    entry_date timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_working_information" PRIMARY KEY (working_information_id),
    CONSTRAINT "FK_working_information_collaborators_collaborator_id" FOREIGN KEY (collaborator_id) REFERENCES public.collaborators (collaborator_id) ON DELETE CASCADE,
    CONSTRAINT "FK_working_information_sub_catalogs_BranchId" FOREIGN KEY ("BranchId") REFERENCES public.sub_catalogs (sub_catalog_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_working_information_sub_catalogs_WorkAreaId" FOREIGN KEY ("WorkAreaId") REFERENCES public.sub_catalogs (sub_catalog_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_working_information_sub_catalogs_WorkPositionId" FOREIGN KEY ("WorkPositionId") REFERENCES public.sub_catalogs (sub_catalog_id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_catalogs_company_type" ON public.catalogs (company_id, catalog_name, catalog_type);

CREATE UNIQUE INDEX "IX_collaborator_id" ON public.collaborators (collaborator_id);

CREATE UNIQUE INDEX "IX_collaborators_collaborator_code" ON public.collaborators (collaborator_code);

CREATE INDEX "IX_collaborators_company_id" ON public.collaborators (company_id);

CREATE UNIQUE INDEX "IX_collaborators_identification_number" ON public.collaborators (identification_number);

CREATE UNIQUE INDEX "IX_companies_code" ON public.companies (code);

CREATE UNIQUE INDEX "IX_companies_id" ON public.companies (company_id);

CREATE INDEX ix_modules_company_code ON public.modules (code);

CREATE INDEX ix_permission_id ON public.permissions (permission_id);

CREATE INDEX "IX_permissions_role_id" ON public.permissions (role_id);

CREATE UNIQUE INDEX ix_permit_application_id ON public.permit_applications (permit_application_id);

CREATE INDEX "IX_permit_applications_collaborator_id" ON public.permit_applications (collaborator_id);

CREATE UNIQUE INDEX "IX_personal_informations_collaborator_id" ON public.personal_informations (collaborator_id);

CREATE INDEX ix_role_id ON public.roles (role_id);

CREATE UNIQUE INDEX "IX_salaries_collaborator_id" ON public.salaries (collaborator_id);

CREATE INDEX ix_session_id ON public.sessions (session_id);

CREATE INDEX "IX_sessions_user_id" ON public.sessions (user_id);

CREATE INDEX "IX_sub_catalogs_catalog_id" ON public.sub_catalogs (catalog_id);

CREATE UNIQUE INDEX "IX_Unique_User_Module_Role" ON public.user_module_roles (user_profile_id, module_code);

CREATE INDEX "IX_user_module_roles_module_id" ON public.user_module_roles (module_id);

CREATE INDEX "IX_user_module_roles_role_id" ON public.user_module_roles (role_id);

CREATE INDEX "IX_users_profiles_company_id" ON public.users_profiles (company_id);

CREATE INDEX "IX_users_profiles_user_id" ON public.users_profiles (user_id);

CREATE UNIQUE INDEX "IX_vacations_collaborator_id" ON public.vacations (collaborator_id);

CREATE INDEX "IX_working_information_BranchId" ON public.working_information ("BranchId");

CREATE UNIQUE INDEX "IX_working_information_collaborator_id" ON public.working_information (collaborator_id);

CREATE INDEX "IX_working_information_WorkAreaId" ON public.working_information ("WorkAreaId");

CREATE INDEX "IX_working_information_WorkPositionId" ON public.working_information ("WorkPositionId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260406195907_InitialMigration', '10.0.5');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260406212344_AgregarCampoOpcionalesPermisos', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE public.working_information DROP CONSTRAINT "FK_working_information_sub_catalogs_BranchId";

ALTER TABLE public.working_information DROP CONSTRAINT "FK_working_information_sub_catalogs_WorkAreaId";

ALTER TABLE public.working_information DROP CONSTRAINT "FK_working_information_sub_catalogs_WorkPositionId";

ALTER TABLE public.personal_informations DROP COLUMN departament;

ALTER TABLE public.working_information RENAME COLUMN "WorkPositionId" TO work_position_id;

ALTER TABLE public.working_information RENAME COLUMN "WorkAreaId" TO work_area_id;

ALTER TABLE public.working_information RENAME COLUMN "BranchId" TO branch_id;

ALTER INDEX public."IX_working_information_WorkPositionId" RENAME TO "IX_working_information_work_position_id";

ALTER INDEX public."IX_working_information_WorkAreaId" RENAME TO "IX_working_information_work_area_id";

ALTER INDEX public."IX_working_information_BranchId" RENAME TO "IX_working_information_branch_id";

ALTER TYPE public.catalog_type_enum ADD VALUE 'departaments';
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

ALTER TABLE public.personal_informations ADD departament_id integer;

ALTER TABLE public.catalogs ADD is_global boolean NOT NULL DEFAULT FALSE;

CREATE INDEX "IX_personal_informations_departament_id" ON public.personal_informations (departament_id);

ALTER TABLE public.personal_informations ADD CONSTRAINT "FK_personal_informations_sub_catalogs_departament_id" FOREIGN KEY (departament_id) REFERENCES public.sub_catalogs (sub_catalog_id) ON DELETE RESTRICT;

ALTER TABLE public.working_information ADD CONSTRAINT "FK_working_information_sub_catalogs_branch_id" FOREIGN KEY (branch_id) REFERENCES public.sub_catalogs (sub_catalog_id) ON DELETE RESTRICT;

ALTER TABLE public.working_information ADD CONSTRAINT "FK_working_information_sub_catalogs_work_area_id" FOREIGN KEY (work_area_id) REFERENCES public.sub_catalogs (sub_catalog_id) ON DELETE RESTRICT;

ALTER TABLE public.working_information ADD CONSTRAINT "FK_working_information_sub_catalogs_work_position_id" FOREIGN KEY (work_position_id) REFERENCES public.sub_catalogs (sub_catalog_id) ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260407214132_AgregarCatalogGlobales', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE public.catalogs ALTER COLUMN company_id DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260407225840_AgregarOpcionalCatalog', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE public.catalogs ALTER COLUMN is_global SET DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260407231705_IsGlobalIsRequered', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TYPE public.permit_application_type_enum ADD VALUE 'donated_vacations';
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

ALTER TABLE public.permit_applications ADD identification_collaborator_to_receive text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260408230959_AgregarCampoParaSolicitarPermiso', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE public.permit_applications ALTER COLUMN amount_days TYPE numeric(18,4);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260408234813_CambiarTiposDatos', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE public.vacations ADD donated_vacation numeric(18,4) NOT NULL DEFAULT 0.0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260409181345_AgregarCampoVacacacionesDonadas', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE public.permit_applications ALTER COLUMN start_date DROP NOT NULL;

ALTER TABLE public.permit_applications ALTER COLUMN end_date DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260409181935_OpcionalCampoSolicitudes', '10.0.5');

COMMIT;

START TRANSACTION;
DROP INDEX public."IX_collaborators_identification_number";

CREATE INDEX "IX_collaborators_identification_number" ON public.collaborators (identification_number);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260410220312_DropIndex', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE public.permit_applications RENAME COLUMN rejected_by TO "RejectedBy";

ALTER TABLE public.permit_applications RENAME COLUMN approved_by TO "ApprovedBy";

ALTER TABLE public.users ADD "AreaId" integer NOT NULL DEFAULT 0;

ALTER TABLE public.permit_applications ADD additional_data jsonb NOT NULL DEFAULT '{}';

ALTER TABLE public.permit_applications ADD administrator_fullname text;

ALTER TABLE public.permit_applications ADD first_step_approved boolean;

ALTER TABLE public.permit_applications ADD manager_fullname text;

ALTER TABLE public.permit_applications ADD second_step_approved boolean;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260411012953_CambiarEntidadPermisos', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE public.permit_applications DROP COLUMN "ApprovedBy";

ALTER TABLE public.permit_applications DROP COLUMN "RejectedBy";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260411013249_EliminarColumna', '10.0.5');

COMMIT;

START TRANSACTION;
CREATE TYPE public.deduction_type_enum AS ENUM ('loans', 'advance_christmas_bonus', 'late_arrivals', 'other_deductions');
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE public.deductions (
    deduction_id uuid NOT NULL DEFAULT (gen_random_uuid()),
    deduction_type deduction_type_enum NOT NULL,
    "Description" text,
    collaborator_id uuid NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_deductions" PRIMARY KEY (deduction_id),
    CONSTRAINT "FK_deductions_collaborators_collaborator_id" FOREIGN KEY (collaborator_id) REFERENCES public.collaborators (collaborator_id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX ix_deduction_id ON public.deductions (deduction_id);

CREATE INDEX "IX_deductions_collaborator_id" ON public.deductions (collaborator_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260414171639_AgregarDeduciones', '10.0.5');

COMMIT;

START TRANSACTION;
CREATE TYPE public.payroll_status_enum AS ENUM ('progress', 'closed', 'cancelled', 'completed');
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE public.payrolls (
    payroll_id uuid NOT NULL DEFAULT (gen_random_uuid()),
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone,
    total_to_pay numeric NOT NULL DEFAULT 0.0,
    "Status" payroll_status_enum NOT NULL,
    "CompanyId" uuid NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_payrolls" PRIMARY KEY (payroll_id),
    CONSTRAINT "FK_payrolls_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES public.companies (company_id) ON DELETE RESTRICT
);

CREATE TABLE public."WorkPositionHistory" (
    "Id" uuid NOT NULL,
    "CollaboratorId" uuid NOT NULL,
    "WorkPositionId" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_WorkPositionHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkPositionHistory_collaborators_CollaboratorId" FOREIGN KEY ("CollaboratorId") REFERENCES public.collaborators (collaborator_id) ON DELETE CASCADE,
    CONSTRAINT "FK_WorkPositionHistory_sub_catalogs_WorkPositionId" FOREIGN KEY ("WorkPositionId") REFERENCES public.sub_catalogs (sub_catalog_id) ON DELETE CASCADE
);

CREATE TABLE public.ordinary_payrolls (
    ordinary_payroll_id uuid NOT NULL DEFAULT (gen_random_uuid()),
    ir numeric(18,4) NOT NULL,
    inss numeric(18,4) NOT NULL,
    bonus numeric(18,4) NOT NULL,
    overtimes numeric(18,4) NOT NULL,
    deductions numeric(18,4) NOT NULL,
    gross_salary numeric(18,4) NOT NULL,
    vacations numeric(18,4) NOT NULL,
    total_to_pay numeric(18,4) NOT NULL,
    total_deductions numeric(18,4) NOT NULL,
    payroll_id uuid NOT NULL,
    collaborator_id uuid NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_ordinary_payrolls" PRIMARY KEY (ordinary_payroll_id),
    CONSTRAINT "FK_ordinary_payrolls_collaborators_collaborator_id" FOREIGN KEY (collaborator_id) REFERENCES public.collaborators (collaborator_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_ordinary_payrolls_payrolls_payroll_id" FOREIGN KEY (payroll_id) REFERENCES public.payrolls (payroll_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_ordinary_payroll_id ON public.ordinary_payrolls (ordinary_payroll_id);

CREATE INDEX "IX_ordinary_payrolls_collaborator_id" ON public.ordinary_payrolls (collaborator_id);

CREATE INDEX "IX_ordinary_payrolls_payroll_id" ON public.ordinary_payrolls (payroll_id);

CREATE UNIQUE INDEX ix_payroll_id ON public.payrolls (payroll_id);

CREATE INDEX "IX_payrolls_CompanyId" ON public.payrolls ("CompanyId");

CREATE INDEX "IX_WorkPositionHistory_CollaboratorId" ON public."WorkPositionHistory" ("CollaboratorId");

CREATE INDEX "IX_WorkPositionHistory_WorkPositionId" ON public."WorkPositionHistory" ("WorkPositionId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260416190821_AgregarTablasNominasAndDeducciones', '10.0.5');

COMMIT;

